// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSet(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeleteSet(arg1:string,arg2:string):Promise<void>;

export function GetSkins():Promise<Record<string, any>>;

export function LoginWithDiscord():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function UpdateSet(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function UploadImage(arg1:string):Promise<Record<string, string>>;
