// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSet(arg1, arg2) {
  return window['go']['main']['App']['CreateSet'](arg1, arg2);
}

export function DeleteSet(arg1, arg2) {
  return window['go']['main']['App']['DeleteSet'](arg1, arg2);
}

export function GetSkins() {
  return window['go']['main']['App']['GetSkins']();
}

export function LoginWithDiscord() {
  return window['go']['main']['App']['LoginWithDiscord']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function UpdateSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSet'](arg1, arg2, arg3);
}

export function UploadImage(arg1) {
  return window['go']['main']['App']['UploadImage'](arg1);
}
